# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def pods
  pod 'Alamofire'     ,'~>5.0'
  pod 'Kingfisher'    ,'~>5.0'
  pod 'ReactorKit'    ,'~>2.0'
  pod 'RxCocoa'       ,'~>5.0'
  pod 'RxDataSources' ,'~>4.0'
  pod 'SwiftyJSON'    ,'~>4.0'
end
   
target 'MVVM' do
  pods
end

target 'MVVMTests' do
  pods
end
