# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM

  pod 'Alamofire'	    ,'~>5.0'
  pod 'SDWebImage'    ,'~>4.2.2'
  pod 'ReactorKit'	  ,'~>2.0'
  pod 'RxCocoa'	      ,'~>5.0'
  pod 'RxDataSources' ,'~>4.0'
  pod 'SwiftyJSON'    ,'~>4.0'
end
